# Generated by Django 3.2.8 on 2022-09-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matnlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='-', max_length=40, null=True)),
                ('title', models.CharField(default='-', max_length=50, null=True)),
                ('text', models.TextField(default='-', max_length=500, null=True, verbose_name='Text')),
                ('text_ru', models.TextField(default='-', max_length=500, null=True, verbose_name='Text Ru')),
            ],
            options={
                'verbose_name': 'Matn',
                'verbose_name_plural': 'Matnlar',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='lang',
            field=models.CharField(choices=[('Ru', 'Ru'), ('Uz', 'Uz')], default='Uz', max_length=33, null=True, verbose_name='Tili'),
        ),
    ]
