# Generated by Django 3.2.8 on 2022-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220910_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(default='-', max_length=50, null=True)),
                ('text_ru', models.CharField(default='-', max_length=50, null=True)),
                ('call_back_data', models.CharField(default='-', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
        migrations.AddField(
            model_name='matnlar',
            name='buttons',
            field=models.ManyToManyField(to='backend.Buttons'),
        ),
    ]
