# Generated by Django 3.2.8 on 2022-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_matnlar_row_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matnlar',
            name='buttons',
            field=models.ManyToManyField(null=True, to='backend.Buttons'),
        ),
    ]
