# Generated by Django 3.2.8 on 2022-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(default='-', max_length=30, null=True, verbose_name='Ismi')),
                ('surname', models.CharField(default='-', max_length=30, null=True, verbose_name='Familiyasi')),
                ('nationality', models.CharField(default='-', max_length=30, null=True, verbose_name='Irqi')),
                ('passport_number', models.CharField(default='-', max_length=55, null=True, verbose_name='Passport raqami')),
                ('contact_number', models.CharField(default='-', max_length=60, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(default='-', max_length=254, null=True)),
                ('appointment_category', models.CharField(choices=[('National Visa (Type D)', 'Type D'), ('National Visa (Type C)', 'Type C'), ('Reconsideration', 'Reconsideration')], default='National Visa (Type D)', max_length=70, null=True, verbose_name='Tayinlash toifasi')),
                ('sub_category', models.CharField(choices=[('Higher education', 'Higher Education'), ('Turkish citizens - work permit', 'Turkish Citizens'), ('Foreigners - work permit', 'Foreigners'), ('Long-Stay others', 'Long Stay')], default='Foreigners - work permit', max_length=100, null=True, verbose_name='Pastki kategoriya')),
                ('visa_aplication_centre', models.CharField(default='-', max_length=100, null=True, verbose_name='Application')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
