# Generated by Django 3.2.8 on 2022-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220908_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('Ru', 'Ru'), ('Uz', 'Uz')], default='Uz', max_length=33, null=True, verbose_name='Tili')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(default='-', max_length=55, null=True)),
            ],
            options={
                'verbose_name': 'Bot user',
                'verbose_name_plural': 'Bot users',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
